# Generated by Django 4.1.1 on 2022-09-20 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image_url', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.CharField(max_length=50)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_notes', models.TextField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_items', models.ManyToManyField(to='cake_me_app.cake')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake_me_app.cake')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake_me_app.order')),
            ],
        ),
    ]
