# Generated by Django 4.1.1 on 2022-09-23 20:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cake_me_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeMeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Enter your username', max_length=50)),
                ('email', models.EmailField(help_text='Enter your email', max_length=50, unique=True)),
                ('password', models.CharField(help_text='Enter your password', max_length=50)),
                ('telephone', models.CharField(help_text='Enter your telephone', max_length=20)),
                ('gender', models.CharField(help_text='Enter your Gender', max_length=6)),
            ],
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='cake',
            new_name='cake_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='cake',
            name='category',
            field=models.CharField(default='Sponge', help_text='Enter the category of the cake', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Enter the date of the order'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.FloatField(default=0, help_text='Enter the total cost of the order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cake_me_app.order'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='description',
            field=models.TextField(help_text='Enter the description of the cake'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='image_url',
            field=models.TextField(help_text='Enter the image url of the cake'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='name',
            field=models.CharField(help_text='Enter the name of the cake', max_length=50),
        ),
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.IntegerField(help_text='Enter the price of the cake'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(to='cake_me_app.orderitem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Enter the quantity of the cake'),
        ),
        migrations.AddField(
            model_name='order',
            name='userId',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='cake_me_app.cakemeuser'),
        ),
    ]
