# Generated by Django 4.1.1 on 2022-09-27 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_me_app', '0002_cakemeuser_rename_cake_orderitem_cake_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cake_me_app.cakemeuser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.FloatField(help_text='Enter the total cost of the order'),
        ),
    ]
