# Generated by Django 4.1.1 on 2022-09-27 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_me_app', '0004_rename_cake_id_orderitem_cake_alter_order_total_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='cake',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cake_me_app.cake'),
        ),
    ]
