# Generated by Django 4.1.1 on 2022-09-29 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake_me_app', '0007_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
