# Generated by Django 4.1.1 on 2022-09-29 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake_me_app', '0013_cakeorderitem_delete_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cakeorderitem',
            name='order',
        ),
    ]
