# Generated by Django 4.1.1 on 2022-09-29 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_me_app', '0014_remove_cakeorderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakeorderitem',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cake_me_app.order'),
        ),
    ]
