# Generated by Django 4.1.1 on 2022-09-29 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_me_app', '0015_cakeorderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakeorderitem',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cake_me_app.order'),
        ),
    ]
