# Generated by Django 4.1.1 on 2022-09-29 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake_me_app', '0016_alter_cakeorderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cakeorderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
