# Generated by Django 4.1.1 on 2022-09-29 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake_me_app', '0018_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_items',
            new_name='items',
        ),
    ]
