# Generated by Django 4.1.1 on 2022-09-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_me_app', '0019_rename_order_items_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakeorderitem',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Enter the quantity of the cake'),
        ),
    ]
